import type { Metadata } from "next";
import "./globals.css";
import { CartProvider } from "@/lib/cart-context";
import { OrderProvider } from "@/lib/order-context";
import { AuthProvider } from "@/lib/auth-context";
import { ConditionalLayout } from "@/components/layout/conditional-layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="antialiased sf-mono-font"
      >
        <OrderProvider>
          <CartProvider>
            <AuthProvider>
              <ConditionalLayout>{children}</ConditionalLayout>
            </AuthProvider>
          </CartProvider>
        </OrderProvider>
      </body>
    </html>
  );
}
